import { useEffect, useId, useState } from 'react';
export function BrandLogo() { return <img className="clearroute-wordmark" src="/branding/clearroute-wordmark.svg" alt="ClearRoute" width="220" height="51"/>; }
export function DnaBackdrop() { return <div className="route-dna" aria-hidden="true"><DnaArt /></div>; }
export function DnaArt() {
 const id = useId().replaceAll(':','');
 const [tilt, setTilt] = useState({ x: 0, y: 0 });
 useEffect(() => { const move = (event: PointerEvent) => setTilt({ x: ((event.clientY / Math.max(1, window.innerHeight)) - .5) * -12, y: ((event.clientX / Math.max(1, window.innerWidth)) - .5) * 16 }); window.addEventListener('pointermove', move, { passive: true }); return () => window.removeEventListener('pointermove', move); }, []);
 const points = Array.from({length:65}, (_, i) => { const phase=i*Math.PI/16; return {x:35+i*8.2, a:155+83*Math.sin(phase), b:155-83*Math.sin(phase), depth:Math.cos(phase)}; });
 return <svg className="dna-art" style={{ transform: `perspective(900px) translate3d(${tilt.y / 3}px, ${tilt.x / 3}px, 0) rotateX(${tilt.x}deg) rotateY(${tilt.y}deg)` }} viewBox="0 0 600 330" fill="none" aria-hidden="true"><defs><linearGradient id={id} x1="0" y1="0" x2="600" y2="330" gradientUnits="userSpaceOnUse"><stop stopColor="#65e4fa"/><stop offset=".5" stopColor="#49acd1"/><stop offset="1" stopColor="#b9edff"/></linearGradient></defs><g stroke={`url(#${id})`}><polyline points={points.map(p=>`${p.x},${p.a}`).join(' ')} strokeWidth="14" opacity=".08"/><polyline points={points.map(p=>`${p.x},${p.b}`).join(' ')} strokeWidth="14" opacity=".08"/>{points.filter((_,i)=>i%2===0).map((p,i)=><g key={i} opacity={.25+.6*Math.abs(p.depth)}><path d={`M${p.x} ${p.a}V${p.b}`} strokeWidth="1.5"/><circle cx={p.x} cy={p.a} r="3.5" fill="#87e9fa"/><circle cx={p.x} cy={p.b} r="3.5" fill="#50add5"/></g>)}<polyline points={points.map(p=>`${p.x},${p.a}`).join(' ')} strokeWidth="3"/><polyline points={points.map(p=>`${p.x},${p.b}`).join(' ')} strokeWidth="3"/></g><g fill="#8ecfe5" opacity=".4">{points.filter((_,i)=>i%5===0).map((p,i)=><circle key={i} cx={p.x} cy={25+(i*47)%280} r="1.5"/>)}</g></svg>;
}
