import { useAccountStorage } from './account-storage';
import { apiFetch } from './http';
import { useEffect, useState } from 'react';
import type { Session } from './types';
type Purchase={id:string;bytes:number;status:string;createdAt:string;error:string|null;response:any;evidence:any;target:{party:string;domain:string}};
type State={target:{party:string;domain:string;minBytes:number;balanceCc:string;checkedAt:string}|null;error:string|null;maxBytes:number;remainingLimitBytes:number;purchases:Purchase[]};
export default function Traffic({session}:{session:Session}){
  const storage = useAccountStorage();
 const [state,setState]=useState<State|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[amount,setAmount]=useState('200000');
 const [saved,setSaved]=useState<{key:string;bytes:number}|null>(()=>{try{return JSON.parse(storage.getItem('clearroute.traffic.pending')||'null');}catch{return null;}});
 async function refresh(signal?:AbortSignal){const r=await apiFetch('/api/traffic',{headers:{'x-demo-session':session},signal});const data=await r.json();if(!r.ok)throw new Error(data.error?.message||'Traffic service unavailable');setState(data);}
 useEffect(()=>{if(session!=='operator')return;const controller=new AbortController();const update=()=>void refresh(controller.signal).catch(e=>{if(!controller.signal.aborted)setError(e.message);});update();const timer=setInterval(update,5000);return()=>{clearInterval(timer);controller.abort();};},[session]);
 if(session!=='operator')return <section className="card localnet-intro"><h2>Provider traffic purchases</h2><p>Switch to the local operator role to manage the shared validator’s capacity. Traffic purchases are not customer usage charges.</p></section>;
 const unresolved=state?.purchases.some(p=>!['completed','failed','rejected'].includes(p.status));
 async function purchase(){
   const operation=saved||{key:crypto.randomUUID(),bytes:Number(amount)};
   setSaved(operation);storage.setItem('clearroute.traffic.pending',JSON.stringify(operation));setBusy(true);setError('');
   try{const r=await apiFetch('/api/traffic',{method:'POST',headers:{'x-demo-session':session,'content-type':'application/json','idempotency-key':operation.key},body:JSON.stringify({bytes:operation.bytes})});const data=await r.json();if(!r.ok){if(r.status<500){setSaved(null);storage.removeItem('clearroute.traffic.pending');}throw new Error(data.error?.message||'Could not verify purchase');}setSaved(null);storage.removeItem('clearroute.traffic.pending');await refresh();}catch(e){setError(e instanceof Error?e.message:'Response unknown. Check the saved request.');}finally{setBusy(false);}
 }
 async function reconcile(id:string){setBusy(true);setError('');try{const r=await apiFetch(`/api/traffic/${encodeURIComponent(id)}/reconcile`,{method:'POST',headers:{'x-demo-session':session,'content-type':'application/json'},body:'{}'});const data=await r.json();if(!r.ok)throw new Error(data.error?.message||'Status check failed');setState(data);}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <div className="localnet-workspace"><section className="card localnet-intro"><div className="card-heading"><div><span className="eyebrow">NATIVE PURCHASE · LOCALNET TEST CC</span><h2>Buy shared validator traffic</h2></div><span className={`badge ${state?.target?'good':'neutral'}`}>{state?.target?'Wallet connected':'Wallet unavailable'}</span></div>
 <p>This spends the provider wallet’s LocalNet test CC to buy capacity for its validator. It does not send CC to a customer or create an invoice.</p>
 {state?.target && <><p><strong>{state.target.balanceCc} test CC</strong> unlocked · Minimum {state.target.minBytes.toLocaleString()} bytes · Maximum {state.maxBytes.toLocaleString()} bytes per purchase.</p><label className="field">Traffic bytes<input type="number" min={state.target.minBytes} max={Math.min(state.maxBytes,state.remainingLimitBytes)} step="1" value={saved?String(saved.bytes):amount} disabled={busy||!!saved} onChange={e=>setAmount(e.target.value)}/></label><div className="inline-actions"><button className="button" disabled={busy||(!saved&&(!!unresolved||!Number.isSafeInteger(Number(amount))||Number(amount)<state.target.minBytes||Number(amount)>Math.min(state.maxBytes,state.remainingLimitBytes)))} onClick={()=>void purchase()}>{busy?'Checking purchase…':saved?'Check saved purchase':'Buy traffic with test CC'}</button></div><p className="localnet-check">Remaining local test allowance: {state.remainingLimitBytes.toLocaleString()} bytes of 10,000,000. Network price applies at execution. The wallet’s confirmed result is recorded below. Status updates automatically.</p><details><summary>Provider and synchronizer</summary><code className="traffic-id">{state.target.party}</code><code className="traffic-id">{state.target.domain}</code></details></>}
 {(error||state?.error)&&<p role="alert" className="localnet-error">{error||state?.error}</p>}</section>
 <section className="card"><div className="card-heading"><h2>Traffic purchase history</h2></div>{!state?.purchases.length?<div className="empty"><h3>No native traffic purchases yet</h3><p>Confirmed capacity purchases will appear here.</p></div>:state.purchases.map(p=><article className="localnet-run" key={p.id}><div><strong>{p.bytes.toLocaleString()} bytes · {p.status}</strong><time>{new Date(p.createdAt).toLocaleString()}</time></div><code>{p.id}</code>{p.response?.transaction_id&&<><p>Confirmed purchase transaction</p><code>{p.response.transaction_id}</code><p>{p.evidence?'Ledger transaction verified.':'Wallet confirmed; ledger evidence pending.'}</p>{p.evidence?.purchase && <p><strong>{p.evidence.purchase.burnedCc} test CC burned</strong> · {p.evidence.purchase.bytes.toLocaleString()} bytes purchased. Protocol conversion: {p.evidence.purchase.protocolUsdPerCc} USD/CC (not a market quote).</p>}</>}{p.response?.failure_reason&&<p>Failure: {p.response.failure_reason}</p>}{p.error&&<p className="localnet-error">{p.error}</p>}{!['completed','failed','rejected'].includes(p.status)&&<button className="button secondary" disabled={busy} onClick={()=>void reconcile(p.id)}>Check purchase status</button>}</article>)}</section>
 <div className="info-note"><p>Purchased capacity is shared by the validator. Remaining traffic and customer-attributed bytes are separate measurements. CC burned is shown only when verified from the purchase transaction. Wallet balance changes can include rewards and other activity.</p></div></div>;
}
