import {useEffect,useState} from 'react';
import type {Session} from './types';
export default function Metering({session}:{session:Session}){
 const [state,setState]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState('');
 async function request(route='',body?:unknown,signal?:AbortSignal){const r=await fetch('/api/metering'+route,{method:body?'POST':'GET',headers:{'x-demo-session':session,'content-type':'application/json'},body:body?JSON.stringify(body):undefined,signal});const data=await r.json();if(!r.ok)throw new Error(data.error?.message||'Metering unavailable');return data;}
 useEffect(()=>{const c=new AbortController();const refresh=()=>void request('',undefined,c.signal).then(setState).catch(e=>{if(!c.signal.aborted)setError(e.message);});refresh();const timer=setInterval(refresh,15000);return()=>{c.abort();clearInterval(timer);};},[session]);
 async function act(route:string,body:unknown){setBusy(true);setError('');try{await request(route,body);setState(await request());}catch(e){setError(String(e));}finally{setBusy(false);}}
 const options=Object.entries(state?.periods||{}).flatMap(([tenant,periods])=>(periods as string[]).map(start=>({value:tenant+'|'+start,label:tenant+' · '+start.slice(0,10)+' (15 days)'})));
 const choice=options.some(o=>o.value===selected)?selected:options[0]?.value||'';
 return <div className="localnet-workspace"><section className="card localnet-intro"><span className="eyebrow">MEASURED LOCALNET TRAFFIC</span><h2>Customer submission traffic</h2><p>{state?.scope}</p><p>Successful customer submissions are checked against their ledger transactions. Provider work, unmatched submissions, failed submissions and missing evidence are excluded from test charges.</p>{session==='operator'&&<button className="button" disabled={busy} onClick={()=>void act('/sync',{})}>Refresh ledger measurements</button>}{error&&<p role="alert" className="localnet-error">{error}</p>}{state?.cursors.map((c:any)=><p key={c.actor} className={c.error?'localnet-error':'localnet-check'}>{c.actor}: {c.error||`Checked through offset ${c.offset}`} · {c.checkedAt}</p>)}</section>
 <section className="card"><h2>Recorded traffic</h2>{state?.totals.map((t:any)=><p key={t.status}><strong>{t.status.replaceAll('_',' ')}:</strong> {t.bytes===null?'Unavailable':Number(t.bytes).toLocaleString()+' bytes'} · {t.count} submissions</p>)}{!state?.rows.length&&<p>No measurements yet.</p>}{state?.rows.map((r:any)=><details className="localnet-run" key={r.id}><summary>{r.actor} · {r.action} · {r.bytes===null?'Unknown':r.bytes.toLocaleString()+' bytes'} · {r.status.replaceAll('_',' ')}</summary><p>{r.reason}</p><p>Recorded {r.recordTime} · Completion offset {r.offset}</p><code className="traffic-id">{r.updateId||'No transaction reference'}</code><p>Test charge: {r.chargeUsd===null?'Excluded':r.chargeUsd+' USD (fixture)'}</p></details>)}</section>
 <section className="card"><span className="eyebrow">NOT PAYABLE</span><h2>15-day test invoice previews</h2><p>Real measured bytes × 0.000004 USD per byte. This static demo tariff is not a market price or commercial agreement. Windows begin at UTC midnight of the first observed verified usage date and repeat every 15 days. Open periods may be previewed. Snapshots do not collect payment.</p>{session==='operator'&&<><label className="field">Measured billing period<select value={choice} onChange={e=>setSelected(e.target.value)}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label><button className="button" disabled={busy||!choice} onClick={()=>{const [tenantId,periodStart]=choice.split('|');void act('/invoices',{tenantId,periodStart});}}>Create test preview</button></>}{state?.invoices.map((inv:any)=><article className="localnet-run" key={inv.id}><h3>{inv.tenant} · {inv.totalUsd} USD · NOT PAYABLE</h3><code>{inv.id}</code><p>{inv.periodStart.slice(0,10)} to {inv.periodEnd.slice(0,10)} (end exclusive)</p><p>{inv.notice}</p>{inv.lines.map((l:any)=><p key={l.usageId}>{l.action} · {l.bytes.toLocaleString()} bytes · {l.chargeUsd} USD · offset {l.completionOffset}</p>)}</article>)}</section></div>;
}
