import { DatabaseSync } from 'node:sqlite';
import { randomUUID } from 'node:crypto';
import path from 'node:path';
import { z } from 'zod';
import { AppError } from './money.js';
import type { Session } from './store.js';

export const applicationInput = z.object({ id:z.string().regex(/^[a-z][a-z0-9-]{2,63}$/), name:z.string().trim().min(2).max(120), tenantId:z.enum(['atlas','nova']), party:z.string().regex(/^[a-z][a-z0-9-]{2,63}::[a-f0-9]{64,128}$/), participant:z.string().regex(/^[a-z][a-z0-9-]{2,63}$/) }).strict();
export const validatorInput = z.object({ id:z.string().regex(/^[a-z][a-z0-9-]{2,63}$/), name:z.string().trim().min(2).max(120), participant:z.string().regex(/^[a-z][a-z0-9-]{2,63}$/), domain:z.string().regex(/^[a-z][a-z0-9-]{2,63}(\.[a-z0-9-]{1,63})*$/), partyPrefix:z.string().regex(/^[a-z][a-z0-9-]{2,63}$/) }).strict();
type Row=Record<string,unknown>; type App=z.infer<typeof applicationInput>&{status:'pending'|'approved'|'suspended';createdAt:string;approvedAt:string|null;approvedBy:string|null;revision:number;validatorId:string|null}; type Validator=z.infer<typeof validatorInput>&{status:'pending'|'approved'|'suspended';createdAt:string;approvedAt:string|null;approvedBy:string|null;revision:number};
export class OnboardingStore {
  private db:DatabaseSync;
  constructor(directory:string){this.db=new DatabaseSync(directory===':memory:'?':memory:':path.join(directory,'onboarding.sqlite'));this.db.exec(`PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;
CREATE TABLE IF NOT EXISTS applications(id TEXT PRIMARY KEY,name TEXT NOT NULL,tenantId TEXT NOT NULL CHECK(tenantId IN ('atlas','nova')),party TEXT NOT NULL,participant TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('pending','approved','suspended')),createdAt TEXT NOT NULL,approvedAt TEXT,approvedBy TEXT,revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS validators(id TEXT PRIMARY KEY,name TEXT NOT NULL,participant TEXT NOT NULL,domain TEXT NOT NULL,partyPrefix TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('pending','approved','suspended')),createdAt TEXT NOT NULL,approvedAt TEXT,approvedBy TEXT,revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS application_validators(applicationId TEXT PRIMARY KEY REFERENCES applications(id),validatorId TEXT NOT NULL REFERENCES validators(id),boundAt TEXT NOT NULL,boundBy TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS onboarding_audit(id TEXT PRIMARY KEY,at TEXT NOT NULL,actor TEXT NOT NULL,kind TEXT NOT NULL,body TEXT NOT NULL);`);}
  close(){this.db.close();} private event(actor:string,kind:string,body:unknown){this.db.prepare('INSERT INTO onboarding_audit VALUES (?,?,?,?,?)').run(randomUUID(),new Date().toISOString(),actor,kind,JSON.stringify(body));}
  private app(id:string){const r=this.db.prepare('SELECT a.*,av.validatorId FROM applications a LEFT JOIN application_validators av ON av.applicationId=a.id WHERE a.id=?').get(id) as Row|undefined;if(!r)throw new AppError('NOT_FOUND','Application registration not found.',404);return this.appView(r);}
  private val(id:string){const r=this.db.prepare('SELECT * FROM validators WHERE id=?').get(id) as Row|undefined;if(!r)throw new AppError('NOT_FOUND','Validator registration not found.',404);return this.valView(r);}
  private appView(r:Row):App{return{id:String(r.id),name:String(r.name),tenantId:r.tenantId as 'atlas'|'nova',party:String(r.party),participant:String(r.participant),status:r.status as App['status'],createdAt:String(r.createdAt),approvedAt:r.approvedAt?String(r.approvedAt):null,approvedBy:r.approvedBy?String(r.approvedBy):null,revision:Number(r.revision),validatorId:r.validatorId?String(r.validatorId):null};}
  private valView(r:Row):Validator{return{id:String(r.id),name:String(r.name),participant:String(r.participant),domain:String(r.domain),partyPrefix:String(r.partyPrefix),status:r.status as Validator['status'],createdAt:String(r.createdAt),approvedAt:r.approvedAt?String(r.approvedAt):null,approvedBy:r.approvedBy?String(r.approvedBy):null,revision:Number(r.revision)};}
  private operator(s:Session){if(s.role!=='operator')throw new AppError('FORBIDDEN','An operator account is required for onboarding administration.',403);} private owner(s:Session,t:string){if(s.role!=='operator'&&s.tenantId!==t)throw new AppError('FORBIDDEN','This account cannot manage another customer application.',403);}
  state(s:Session){const scoped=s.role==='operator'?'':' WHERE a.tenantId=?',args=s.role==='operator'?[]:[s.tenantId];const applications=(this.db.prepare('SELECT a.*,av.validatorId FROM applications a LEFT JOIN application_validators av ON av.applicationId=a.id'+scoped+' ORDER BY a.createdAt DESC').all(...args) as Row[]).map(r=>this.appView(r));const all=(this.db.prepare('SELECT * FROM validators ORDER BY createdAt DESC').all() as Row[]).map(r=>this.valView(r));const validators=s.role==='operator'?all:all.filter(v=>applications.some(a=>a.validatorId===v.id));const audit=(this.db.prepare('SELECT * FROM onboarding_audit ORDER BY at DESC LIMIT 100').all() as Row[]).map(r=>({id:String(r.id),at:String(r.at),actor:String(r.actor),kind:String(r.kind),body:JSON.parse(String(r.body))}));return{applications,validators,audit};}
  registerApplication(s:Session,input:unknown){const b=applicationInput.parse(input);this.owner(s,b.tenantId);this.db.exec('BEGIN IMMEDIATE');try{if(this.db.prepare('SELECT id FROM applications WHERE id=?').get(b.id))throw new AppError('APPLICATION_EXISTS','Application ID is already registered.',409);const now=new Date().toISOString();this.db.prepare('INSERT INTO applications(id,name,tenantId,party,participant,status,createdAt) VALUES (?,?,?,?,?,?,?)').run(b.id,b.name,b.tenantId,b.party,b.participant,'pending',now);this.event(s.id,'application.registered',b);this.db.exec('COMMIT');}catch(e){this.db.exec('ROLLBACK');throw e;}return this.app(b.id);}
  registerValidator(s:Session,input:unknown){this.operator(s);const b=validatorInput.parse(input);this.db.exec('BEGIN IMMEDIATE');try{if(this.db.prepare('SELECT id FROM validators WHERE id=?').get(b.id))throw new AppError('VALIDATOR_EXISTS','Validator ID is already registered.',409);const now=new Date().toISOString();this.db.prepare('INSERT INTO validators(id,name,participant,domain,partyPrefix,status,createdAt) VALUES (?,?,?,?,?,?,?)').run(b.id,b.name,b.participant,b.domain,b.partyPrefix,'pending',now);this.event(s.id,'validator.registered',b);this.db.exec('COMMIT');}catch(e){this.db.exec('ROLLBACK');throw e;}return this.val(b.id);}
  approveApplication(s:Session,id:string){this.operator(s);const c=this.app(id);if(c.status==='approved')return c;if(c.status==='suspended')throw new AppError('APPLICATION_SUSPENDED','Suspended applications must be re-registered.',409);this.db.prepare("UPDATE applications SET status='approved',approvedAt=?,approvedBy=?,revision=revision+1 WHERE id=?").run(new Date().toISOString(),s.id,id);this.event(s.id,'application.approved',{id});return this.app(id);}
  approveValidator(s:Session,id:string){this.operator(s);const c=this.val(id);if(c.status==='approved')return c;if(c.status==='suspended')throw new AppError('VALIDATOR_SUSPENDED','Suspended validators must be re-registered.',409);this.db.prepare("UPDATE validators SET status='approved',approvedAt=?,approvedBy=?,revision=revision+1 WHERE id=?").run(new Date().toISOString(),s.id,id);this.event(s.id,'validator.approved',{id});return this.val(id);}
  bind(s:Session,applicationId:string,validatorId:string){this.operator(s);const a=this.app(applicationId),v=this.val(validatorId);if(a.status!=='approved')throw new AppError('APPLICATION_NOT_APPROVED','Approve the application before binding a validator.',409);if(v.status!=='approved')throw new AppError('VALIDATOR_NOT_APPROVED','Approve the validator before binding it.',409);this.db.exec('BEGIN IMMEDIATE');try{this.db.prepare('INSERT INTO application_validators(applicationId,validatorId,boundAt,boundBy) VALUES (?,?,?,?) ON CONFLICT(applicationId) DO UPDATE SET validatorId=excluded.validatorId,boundAt=excluded.boundAt,boundBy=excluded.boundBy').run(applicationId,validatorId,new Date().toISOString(),s.id);this.db.prepare('UPDATE applications SET revision=revision+1 WHERE id=?').run(applicationId);this.event(s.id,'application.validator_bound',{applicationId,validatorId,validatorPartyPrefix:v.partyPrefix});this.db.exec('COMMIT');}catch(e){this.db.exec('ROLLBACK');throw e;}return this.app(applicationId);}
}
