import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {once} from 'node:events';
import {Billing} from './billing.js';
import {Metering} from './metering.js';
import {Store} from './store.js';
import {createApp} from './app.js';
const preview=(tenant='atlas',id='usage-1')=>({id:'preview-'+id,tenant,periodStart:'2026-09-01T00:00:00.000Z',periodEnd:'2026-09-16T00:00:00.000Z',totalUsd:'1.00',payable:false,policy:{id:'measured-fixture-v1',microUsdPerByte:'4'},lines:[{usageId:id,bytes:250000,chargeUsd:'1.00',recordTime:'2026-09-02T00:00:00Z',updateId:'tx-'+id}]});
function fixture(){const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE usage(id TEXT,actor TEXT,status TEXT,recordTime TEXT,bytes INTEGER)');const billing=new Billing(db,()=>Date.parse('2026-09-16T00:00:00Z'));let n=0;return {db,billing,run(fn:()=>any,key='test-operation-'+(++n),payload:any={}){return billing.mutate(key,'test',payload,fn);}};}
test('finalization closes periods once and freezes invoice evidence',()=>{const f=fixture();try{const open={...preview(),periodEnd:'2026-09-17T00:00:00Z'};assert.throws(()=>f.run(()=>f.billing.finalize(open)),/still open/);const inv=f.run(()=>f.billing.finalize(preview()));assert.equal(inv.status,'issued');assert.equal(inv.payable,false);const replay=f.run(()=>f.billing.finalize({...preview(),totalUsd:'2.00'}));assert.deepEqual(replay,inv);assert.equal(f.billing.state().invoices.length,1);assert.equal(f.billing.state().audit.length,1);assert.throws(()=>f.run(()=>f.billing.finalize({...preview('nova'),id:'other'})),/already belongs/);assert.equal(f.billing.state().invoices.length,1);}finally{f.db.close();}});
test('pending payments reserve balance; confirmation, rejection, reversal and partial settlement reconcile exactly',()=>{const f=fixture();try{const inv=f.run(()=>f.billing.finalize(preview()));let current=f.run(()=>f.billing.payment(inv.id,'0.40','BANK-001'));const first=current.payments[0];assert.equal(current.paidUsd,'0.00');assert.throws(()=>f.run(()=>f.billing.payment(inv.id,'0.61','BANK-002')),/exceeds/);current=f.run(()=>f.billing.decide(first.id,'confirmed','Matched test statement'));assert.equal(current.status,'partially_paid');assert.equal(current.outstandingUsd,'0.60');current=f.run(()=>f.billing.payment(inv.id,'0.60','BANK-002'));let second=current.payments.find((p:any)=>p.reference==='BANK-002');current=f.run(()=>f.billing.decide(second.id,'rejected','Incorrect test reference'));assert.equal(current.outstandingUsd,'0.60');assert.throws(()=>f.run(()=>f.billing.decide(second.id,'confirmed','Retry rejected')),/cannot/);current=f.run(()=>f.billing.payment(inv.id,'0.60','BANK-003'));second=current.payments.find((p:any)=>p.reference==='BANK-003');current=f.run(()=>f.billing.decide(second.id,'confirmed','Matched'));assert.equal(current.status,'paid');assert.throws(()=>f.run(()=>f.billing.payment(inv.id,'0.01','BANK-004')),/exceeds/);current=f.run(()=>f.billing.decide(first.id,'reversed','Test payment reversed'));assert.equal(current.paidUsd,'0.60');assert.equal(current.outstandingUsd,'0.40');assert.ok(f.billing.state().audit.some(e=>e.kind==='payment.reversed'));}finally{f.db.close();}});
test('replayed operation, normalized reference and conflicting inputs cannot double-credit',()=>{const f=fixture();try{const inv=f.run(()=>f.billing.finalize(preview()));const first=f.run(()=>f.billing.payment(inv.id,'0.50','bank-001'),'same-operation',{amount:'0.50'});assert.deepEqual(f.run(()=>{throw new Error('Must not run');},'same-operation',{amount:'0.50'}),first);assert.throws(()=>f.run(()=>null,'same-operation',{amount:'0.60'}),/different input/);assert.equal(f.run(()=>f.billing.payment(inv.id,'0.50',' BANK-001 ')).payments.length,1);assert.throws(()=>f.run(()=>f.billing.payment(inv.id,'0.60','BANK-001')),/different details/);assert.equal(f.billing.invoice(inv.id).outstandingUsd,'1.00');}finally{f.db.close();}});
test('late usage is held for review and sandbox clock changes overdue status without changing totals',()=>{const f=fixture();try{const inv=f.run(()=>f.billing.finalize(preview()));f.db.prepare('INSERT INTO usage VALUES (?,?,?,?,?)').run('late','atlas','verified','2026-09-15T23:59:59.999999Z',10);f.db.prepare('INSERT INTO usage VALUES (?,?,?,?,?)').run('next','atlas','verified','2026-09-16T00:00:00.000001Z',10);assert.equal(f.billing.state('atlas').lateUsage.length,1);assert.equal(f.billing.state('nova').lateUsage.length,0);f.run(()=>f.billing.advance());f.run(()=>f.billing.advance());assert.equal(f.billing.invoice(inv.id).status,'overdue');assert.equal(f.billing.invoice(inv.id).totalUsd,'1.00');assert.equal(f.billing.state('nova').audit.length,0);}finally{f.db.close();}});
test('invoice, payment and operation replay persist across database reopen',()=>{const directory=mkdtempSync(path.join(tmpdir(),'billing-persist-'));const file=path.join(directory,'test.sqlite');let db=new DatabaseSync(file);let b=new Billing(db,()=>Date.parse('2026-09-16T00:00:00Z'));const inv=b.mutate('persist-finalize','finalize',{},()=>b.finalize(preview()));const result=b.mutate('persist-payment','payment',{},()=>b.payment(inv.id,'0.20','PERSIST-001'));db.close();db=new DatabaseSync(file);b=new Billing(db);try{assert.equal(b.invoice(inv.id).payments.length,1);assert.deepEqual(b.mutate('persist-payment','payment',{},()=>{throw new Error('Duplicate execution');}),result);}finally{db.close();}});
test('HTTP billing mutations and exports enforce role, tenant, rail, key and body validation',async()=>{
 const directory=mkdtempSync(path.join(tmpdir(),'billing-http-')),m=new Metering(directory,()=>new Map()),store=new Store(path.join(directory,'store.sqlite'));
 const inv=m.billing.mutate('http-finalize','finalize',{},()=>m.billing.finalize(preview()));
 const server=createApp(store,undefined,undefined,undefined,m).listen(0,'127.0.0.1');await once(server,'listening');const url=`http://127.0.0.1:${(server.address() as any).port}/api/billing`;
 const post=(route:string,body:any,role='operator',key='http-test-operation')=>fetch(url+route,{method:'POST',headers:{'x-demo-session':role,'content-type':'application/json','idempotency-key':key},body:JSON.stringify(body)});
 try{const nova=await(await fetch(url,{headers:{'x-demo-session':'nova'}})).json();assert.equal(nova.invoices.length,0);assert.equal(nova.audit.length,0);assert.equal((await fetch(url+'/invoices/'+inv.id+'/export',{headers:{'x-demo-session':'nova'}})).status,404);assert.equal((await fetch(url+'/invoices/'+inv.id+'/export',{headers:{'x-demo-session':'atlas'}})).status,200);for(const route of ['/clock/advance','/finalize','/invoices/'+inv.id+'/payments','/payments/missing/reconcile'])assert.equal((await post(route,{},'atlas')).status,403);assert.equal((await post('/invoices/'+inv.id+'/payments',{amountUsd:'0.20',reference:'TEST-001',rail:'USDC'})).status,400);assert.equal((await post('/clock/advance',{days:15},'operator','')).status,400);assert.equal((await post('/clock/advance',{days:15,live:true})).status,400);assert.equal((await post('/invoices/'+inv.id+'/payments',{amountUsd:'0.20',reference:'TEST-001',rail:'sandbox_usd'})).status,200);}finally{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));m.close();store.close();}
});
